---
title: "COMP/STAT 112 Final Project"
author: "S Khan and R Liu"
output: 
  html_document:
    theme: readable
    highlight: zenburn
    toc: true
    toc_float: true
    df_print: paged
    code_download: true
---

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

```{r libraries}
library(tidyverse)         # for graphing and data cleaning
library(lubridate)         # for working with dates
library(remotes)
library(ggthemes)
library(mudata2)
library(waffle)
library(dplyr)
library(tidyr)
library(readr)
library(magrittr)
library(hrbrthemes)
library(fansi)
library(stringi)
library(ggplot2)
library(ggalt)
library(scales)
library(emojifont)  
theme_set(theme_minimal())
```

```{r data}

Bachelor_Degree_Majors <- read_csv("D:/Macalester College/Courses/Statistics/STAT 112/COMP112-Final-Project/Data/Bachelor_Degree_Majors.csv")

degree_income <- read_csv("D:/Macalester College/Courses/Statistics/STAT 112/COMP112-Final-Project/Data/degrees-that-pay-back.csv")

degrees_over_time <- read_csv("D:/Macalester College/Courses/Statistics/STAT 112/COMP112-Final-Project/Data/1995_2015.csv")
```


## Bachelor's Degree by Gender and Age Group

```{r}
Bachelor_Degree_Majors %>%
  subset(select = -`Age Group`) %>%
  subset(select = -State) %>%
  pivot_longer(-c(Sex, `Bachelor's Degree Holders`),
               names_to = "Degree_Type",
               values_to = "Count",
               values_ptypes = list(num_nests = integer())) %>%
  group_by(Sex, Degree_Type) %>%
  filter(Sex != "Total") %>%
  summarize(num_degree = round(mean(Count)),
            num_total = round(mean(`Bachelor's Degree Holders`))) %>%
  mutate(prop_degree = round(num_degree/num_total*99.8)) %>%
  arrange(desc(prop_degree)) %>%
  mutate(Degree_Type = fct_rev(Degree_Type),
         Degree_Type = fct_reorder(Degree_Type, prop_degree)) %>%
  ggplot(aes(fill = Degree_Type,
             values = prop_degree)) +
  geom_waffle(n_rows = 10, 
              size = 0.1,
              color = "midnightblue") +
  facet_wrap(~Sex) +
  coord_equal() +
  theme_ipsum_rc(grid = "") +
  theme_enhance_waffle() +
  theme_igray() +
  scale_fill_manual(
    name = NULL,
    values = c("cornflowerblue", "palevioletred4", "lightgoldenrod3", "tan2", "slateblue4")) +
  labs(title = "Distribution of Bachelor's Degrees by Gender", 
       subtitle = "",
       fill = "") +
  theme(legend.position = "bottom",
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.title = element_text(size = 13), 
        legend.text = element_text(size = 13)) +
  guides(fill = guide_legend(reverse = TRUE),
         fill = guide_legend(override.aes = list(size = 1)))
```

```{r}
Bachelor_Degree_Majors %>%
  subset(select = -Sex) %>%
  subset(select = -State) %>%
  pivot_longer(-c(`Age Group`, `Bachelor's Degree Holders`),
               names_to = "Degree_Type",
               values_to = "Count",
               values_ptypes = list(num_nests = integer())) %>%
  group_by(`Age Group`, Degree_Type) %>%
  filter(`Age Group` != "25 and older") %>%
  summarize(num_degree = round(mean(Count)),
            num_total = round(mean(`Bachelor's Degree Holders`))) %>%
  mutate(prop_degree = num_degree/num_total*102.2) %>%
  arrange(desc(prop_degree)) %>%
   mutate(Degree_Type = fct_rev(Degree_Type),
         Degree_Type = fct_reorder(Degree_Type, prop_degree)) %>%
  ggplot(aes(fill = Degree_Type,
             values = prop_degree)) +
  geom_waffle(n_rows = 10, 
              size = 0.1,
              color = "midnightblue") +
  facet_wrap(~`Age Group`) +
  coord_equal() +
  theme_ipsum_rc(grid = "") +
  theme_enhance_waffle() +
  theme_igray() +
  scale_fill_manual(
    name = NULL,
    values = c("palevioletred4", "cornflowerblue", "lightgoldenrod3", "tan2", "slateblue4")) +
  labs(title = "Distribution of Bachelor's Degrees by Age Group", 
       subtitle = "",
       fill = "") +
  theme(legend.position = "bottom",
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.title = element_text(size = 13), 
        legend.text = element_text(size = 13)) +
  guides(fill = guide_legend(reverse = TRUE),
         fill = guide_legend(override.aes = list(size = 1)))
```

## Bachelor's Degrees Over Time

```{r}
degrees_over_time %>%
#  subset(select = -c(No_HS_Diploma, HS_Diploma, Some_College_No_Degree, Associate, 
#                     Advanced)) %>%
  subset(select = -Total) %>%
  pivot_longer(-c(Year, Age_Range, Sex),
               names_to = "Degree_Type",
               values_to = "Count",
               values_ptypes = list(num_nests = integer())) %>%
  group_by(Year, Degree_Type) %>%
  summarize(Count = round(mean(Count))) %>%
  arrange(desc(Count)) %>%
  ggplot(aes(x = Year,
             y = Count,
             fill = Degree_Type)) +
  geom_col(width = 5) +
  labs(title = "Attainment of Education Over Time in the US", 
       subtitle = "",
       fill = "") +
  theme_igray() +
  scale_fill_manual(
    name = NULL,
    values = c("darkslateblue", "steelblue4", "tan2", "lightblue4", "azure4", "darkgrey")) +
  theme(legend.position = "bottom",
        axis.title.x = element_blank())
```

## Bachelor's Degrees Income

```{r}
degree_income_exp <- degree_income %>%
  mutate(perc_change = `Percent change from Starting to Mid-Career Salary`,
         major = `Undergraduate Major`,
         st_md_salary = `Starting Median Salary`,
         mid_md_salary = `Mid-Career Median Salary`)

degree_income_starting <- degree_income_exp %>%
  group_by(major) %>%
  summarize(st_md_salary = parse_number(st_md_salary)) %>%
  pivot_wider(names_from = major,
              values_from = st_md_salary) %>%
  mutate(`Science and Engineering` = (`Aerospace Engineering` + 
                                      `Chemical Engineering` + `Civil Engineering` + 
                                      `Electrical Engineering` + 
                                      `Computer Engineering` + 
                                      `Industrial Engineering` + 
                                      `Mechanical Engineering` + Biology + 
                                      Chemistry + Physics + Geology + Sociology + 
                                      Psychology)/13,
         `Science and Engineering Related Fields` = (Agriculture + Architecture + 
                                                    `Computer Science` + 
                                                    Construction + Forestry + 
                                                    Geography + 
                                                    `Information Technology (IT)` + 
                                                    Math + Nursing + Nutrition + 
                                                    `Physician Assistant`)/11,
         Business = (Accounting + `Business Management` + Communications + 
                     Economics + Finance + `Hospitality & Tourism` + 
                     `International Relations` + 
                     `Management Information Systems (MIS)` + Marketing + 
                     `Health Care Administration`)/10,
         Education = Education,
         `Arts, Humanities, and Others` = (Anthropology + `Art History` + 
                                           `Criminal Justice` + Drama + English + 
                                           Film + `Graphic Design` + History + 
                                           `Interior Design` + Journalism + Music + 
                                           Philosophy + `Political Science` + 
                                           Religion + Spanish)/15,
         .keep = "unused") %>%
  pivot_longer(cols = everything(),
               names_to = "Major",
               values_to = "st_md_salary")

degree_income_mid <- degree_income_exp %>%
  group_by(major) %>%
  summarize(mid_md_salary = parse_number(mid_md_salary)) %>%
  pivot_wider(names_from = major,
              values_from = mid_md_salary) %>%
  mutate(`Science and Engineering` = (`Aerospace Engineering` + 
                                      `Chemical Engineering` + `Civil Engineering` + 
                                      `Electrical Engineering` + 
                                      `Computer Engineering` + 
                                      `Industrial Engineering` + 
                                      `Mechanical Engineering` + Biology + 
                                      Chemistry + Physics + Geology + Sociology + 
                                      Psychology)/13,
         `Science and Engineering Related Fields` = (Agriculture + Architecture + 
                                                    `Computer Science` + 
                                                    Construction + Forestry + 
                                                    Geography + 
                                                    `Information Technology (IT)` + 
                                                    Math + Nursing + Nutrition + 
                                                    `Physician Assistant`)/11,
         Business = (Accounting + `Business Management` + Communications + 
                     Economics + Finance + `Hospitality & Tourism` + 
                     `International Relations` + 
                     `Management Information Systems (MIS)` + Marketing + 
                     `Health Care Administration`)/10,
         Education = Education,
         `Arts, Humanities, and Others` = (Anthropology + `Art History` + 
                                           `Criminal Justice` + Drama + English + 
                                           Film + `Graphic Design` + History + 
                                           `Interior Design` + Journalism + Music + 
                                           Philosophy + `Political Science` + 
                                           Religion + Spanish)/15,
         .keep = "unused") %>%
  pivot_longer(cols = everything(),
               names_to = "Major",
               values_to = "mid_md_salary")

degree_income_starting %>%
  left_join(degree_income_mid,
            by = "Major") %>%
  pivot_longer(-Major,
               names_to = "type_salary",
               values_to = "salary") %>%
  arrange(desc(salary)) %>%
  ggplot(aes(x = salary,
             y = Major,
             color = type_salary)) + 
  geom_point(size = 3) + 
  geom_segment(aes(x = 0, 
                   xend = salary, 
                   y = Major, 
                   yend = Major)) +
  labs(title = "Distribution of Median Income by Undergraduate Degree", 
       subtitle = "",
       fill = "") +
  theme_igray() +
  scale_color_manual(
    name = NULL,
    values = c("tomato", "dodgerblue")) +
  theme(legend.position = "bottom",
        axis.title = element_blank())
```

